# Generated by Django 5.1.3 on 2024-11-26 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mv_app.servicio'),
        ),
    ]
